export const common = {
  genericError:
    'Something went wrong on our end. Your work is saved — try again in a moment.',
  offlineBanner: "You're offline. We'll sync your changes when you're back.",
  saved: 'Saved.',
  copied: 'Copied.',
  aiDraftChip: '✨ AI draft',
  aiDraftTooltip:
    'Generated by your AI Co-Founder. Review and edit before using.',
  notFound: {
    title: 'This page doesn’t exist.',
    body: 'It may have been moved or deleted.',
    cta: 'Back to dashboard',
  },
  permissionsError: {
    title: 'You don’t have access to this.',
    body: 'Ask the workspace founder to grant you access to {module}.',
  },
} as const
